global:
  scrape_interval: 5s # Tarik data metrik setiap 5 detik sekali

scrape_configs:
  - job_name: "iris_model_monitoring"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["localhost:8000"] # Mengarah ke server FastAPI kita